# Generated by Django 4.2.3 on 2023-09-12 16:46

import ReadBookApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName)),
                ('decription', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=255)),
                ('authorName', models.CharField(max_length=255)),
                ('publicationName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('buyingPrice', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('discountPrice', models.FloatField()),
                ('bookImage', models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName)),
                ('decription', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('bestseller', models.BooleanField(default=False, help_text='0-normal,1-bestseller')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadBookApp.genre')),
            ],
        ),
    ]
