# Generated by Django 4.2.3 on 2023-09-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookproduct',
            old_name='bestseller',
            new_name='bestSeller',
        ),
        migrations.RenameField(
            model_name='bookproduct',
            old_name='decription',
            new_name='bookDecription',
        ),
        migrations.RenameField(
            model_name='bookproduct',
            old_name='status',
            new_name='bookStatus',
        ),
    ]
