# Generated by Django 4.2.3 on 2023-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0002_rename_bestseller_bookproduct_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='bookLanguage',
            field=models.CharField(choices=[('ta', 'TAMIL'), ('en', 'ENGLISH'), ('hi', 'HINDI'), ('fr', 'FRENCH'), ('no', 'NONE')], default='en', max_length=2),
        ),
    ]
