# Generated by Django 4.2.3 on 2023-09-13 09:26

import ReadBookApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0003_bookproduct_booklanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='bookDecription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='bookLanguage',
            field=models.CharField(choices=[('ta', 'TAMIL'), ('en', 'ENGLISH'), ('fr', 'FRENCH'), ('no', 'NONE')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName),
        ),
    ]
