# Generated by Django 4.2.5 on 2023-09-17 16:54

import ReadBookApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0010_alter_bookproduct_booklanguage_alter_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='translatorName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName),
        ),
    ]
