# Generated by Django 4.2.5 on 2023-09-17 17:27

import ReadBookApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0011_bookproduct_translatorname_alter_genre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproduct',
            name='translatorName',
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName),
        ),
    ]
