# Generated by Django 4.2.5 on 2023-09-20 07:51

import ReadBookApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadBookApp', '0014_alter_genre_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='qty',
            new_name='books_qty',
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ReadBookApp.models.getFileName),
        ),
    ]
